---
title: "About Congre$$"
author: "Andy Wang"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About the Project

[Congre$$](https://github.com/andyzwang/congress) is a project to examine the links between federal political candidate fund-raising and subsequent performance in the actual elections. There's many possible questions that I'd like to answer. Do candidates who receive more small-dollar donors tend to do better in elections? How large is the actual impact of fund-raising on performance? How has the trend of fund-raising changed over the last 30 years? I think that these are all answers with current relevance in our political system, and being able to have some hard data to support our philosophical and moral debates about money in the political atmosphere is very important. I hope to be able to isolate some trends that can provide new perspectives on this conversation.

I have cleaned up my data, but I haven't processed it very far as I want to think mindfully first about how I'd like to use the data provided, which then affects which tables I'd join together and how I process it.

## Data Sources

[The FEC's election data](https://www.fec.gov/data/browse-data/) provides information about all of the contributions of individuals, the fund-raising data of candidates, and much more. I want to figure out which tables I want to join together, especially as I want to see how elections funding has changed over time. However, I have more data than I need in order to be able to complete my project goals.

[MIT Election Lab's data](https://electionlab.mit.edu/data) provides election results on the precinct and district level for candidates, both in the general and in the primary elections, from the years of 1976-2018. This will also be interesting to compare to fundraising data, as certain states and districts have flipped over time due to very targeted fundraising.

## About Me
I am a first-year at Harvard College planning to study Social Studies.